Handle adding more than 50 Annotations in a single check run, differentiate between warnings and errors, ignore errors without an error code
a-b-r-o-w-n/eslint-action pull request #5
Opened 2019-12-02 07:17 UTC by psyked

Apologies for the slightly messy PR, creating this to share as early as possible.

Extended the existing code to add:

1. Support for > 50 Annotations in a single check run
2. Add warnings and errors differently as annotations
3. Skip annotations where the error code is [null] (because this was a failure to parse SCSS files in my case)

2019-12-03 20:44 UTC, a-b-r-o-w-n commented
@psyked thanks for the contribution. I will take a look soon. In the meantime, I noticed some of the references to this git repo were changed to your fork, as well as some of the action configuration. Would you mind reverting those changes? Thanks.

2019-12-03 21:48 UTC, a-b-r-o-w-n requested changes
This looks good with some minor changes requested. Thanks again!

2019-12-03 21:48 UTC, a-b-r-o-w-n commented on src/api.ts
> +  core.info(`PR with files detected: ${pr.files.edges.map(e => e.node.path)}`);
Let's only do this map once and re-use her and in the return object.

2019-12-03 21:48 UTC, a-b-r-o-w-n commented on src/eslint-action.ts
> +          });
Should this be broken down a bit? Adding the annotations to the check and then updating it with a complete status?

2019-12-03 21:48 UTC, a-b-r-o-w-n commented on README.md
> +      - uses: psyked/eslint-action@v1
Please revert.

2019-12-03 21:48 UTC, a-b-r-o-w-n commented on action.yml
> +  color: "purple"
Please revert.

2019-12-03 21:48 UTC, a-b-r-o-w-n commented on package.json
> +  "homepage": "https://github.com/psyked/eslint-action#readme",
Please revert these.

2019-12-07 18:28 UTC, psyked commented on README.md
> +      - uses: psyked/eslint-action@v1
```suggestion
      - uses: a-b-r-o-w-n/eslint-action@v1
```

2019-12-07 18:28 UTC, psyked commented on action.yml
> +  icon: "check-square"
```suggestion
  icon: "check-circle"
```

2019-12-07 18:28 UTC, psyked commented on action.yml
> +  color: "purple"
```suggestion
  color: "yellow"
```

2019-12-07 18:28 UTC, psyked commented on package.json
> +    "url": "https://github.com/psyked/eslint-action/issues"
```suggestion
    "url": "https://github.com/psyked/eslint-action/issues"
```
```suggestion
    "url": "https://github.com/a-b-r-o-w-n/eslint-action/issues"
```

2019-12-07 18:28 UTC, psyked commented on package.json
> +  "homepage": "https://github.com/psyked/eslint-action#readme",
```suggestion
  "homepage": "https://github.com/a-b-r-o-w-n/eslint-action#readme",
```

2019-12-07 18:29 UTC, psyked commented on package.json
> +    "url": "git+https://github.com/psyked/eslint-action.git"
```suggestion
    "url": "git+https://github.com/a-b-r-o-w-n/eslint-action.git"
```

2019-12-11 17:47 UTC, a-b-r-o-w-n approved these changes

2019-12-17 20:41 UTC, a-b-r-o-w-n commented
@psyked is this ready to go? I will merge if so!

2019-12-22 10:06 UTC, psyked commented
> @psyked is this ready to go? I will merge if so!

Apologies - it totally is if you're happy with it 👍 

There's always more to be done on the refactoring front but it's working well enough for me.

2019-12-26 16:11 UTC, merged